version: '3.1'

services:

  database:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - .\work-dir\database:/var/lib/postgresql/data